# Netlify configuration for Next.js app with API routes
# The @netlify/plugin-nextjs handles:
# - API routes -> Netlify functions conversion
# - Client-side routing
# - Static/dynamic page deployment
# - Image optimization

[build]
  command = "npm ci && npm run debug-build && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NEXT_TELEMETRY_DISABLED = "1"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Environment-specific settings
[context.production]
  command = "npm ci && npm run build"
  
[context.production.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[context.deploy-preview]
  command = "npm ci && npm run build"
  
[context.deploy-preview.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[context.branch-deploy]
  command = "npm ci && npm run build"
  
[context.branch-deploy.environment]
  NODE_ENV = "development"
  NEXT_TELEMETRY_DISABLED = "1"

# Plugin configuration - let this handle everything automatically
[[plugins]]
  package = "@netlify/plugin-nextjs" 