[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"
  NEXT_TELEMETRY_DISABLED = "1"

# Next.js API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# API headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Handle client-side routing (SPA fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment-specific settings
[context.production]
  command = "npm run build"
  
[context.production.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[context.deploy-preview]
  command = "npm run build"
  
[context.deploy-preview.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[context.branch-deploy]
  command = "npm run build"
  
[context.branch-deploy.environment]
  NODE_ENV = "development"
  NEXT_TELEMETRY_DISABLED = "1"

# Functions configuration for API routes
[functions]
  directory = ".netlify/functions/"
  node_bundler = "esbuild"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Form handling (if needed for contact forms)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true 